### ISSUE TITLE
プロフィールや検索画面の80%クリア要速度はよく違っている

### ISSUE THREAD

**Issue by Chronopolize** [garplab/typingtube#72]
例：https://typing-tube.net/my/movies?keyword=symmetric+rose 
「Symmetric Rose」という曲の80%速度は6.0けど、実際は~3.0辺りです。
よく見かけるすバグです。これはもしかして初めて曲を投稿した時の値かもしれない。

**Comment by fire1192** [comment]
#66 のこの譜面では一度も16type/secという速度には達していないので初めて曲を投稿した時の値ではないと思います。よく見かけるバグなので原因を見つけたいですね。
I think the reason of this bug may not set the value of our first submitted because no value greater than 10 type / sec in #66's score. It's true that this bug is very common, so I hope it's fixed as soon as possible.

**Comment by Chronopolize** [comment]
確かに優先して調べてほしいバグですね。情報ありがとうございます。複製スレッドなのでこちらを閉じます。
